// Copyright 2026 The Netie Open HBM Authors
// SPDX-License-Identifier: Apache-2.0
`default_nettype none
`timescale 1ns/1ps

// addr_map -- top-level wrapper for the programmable XOR address mapper.
//
//   sa_i  -> region table -> XOR mapper -> pa_o
//
// Latency: 1 cycle (registered output). Throughput: 1 mapping per cycle.
//
// CSR access is via APB to a small register file (see addr_map_reg_top.sv,
// generated by util/reggen/regtool.py from data/addr_map.hjson). For the
// Phase-0 scaffolding the register interface is exposed as a flat bundle
// to keep this file standalone.
module addr_map
  import addr_map_pkg::*;
(
  input  logic                  clk_i,
  input  logic                  rst_ni,

  // Request side
  input  logic                  req_valid_i,
  output logic                  req_ready_o,
  input  logic [SaW-1:0]        req_sa_i,
  input  op_e                   req_op_i,

  // Response side
  output logic                  rsp_valid_o,
  input  logic                  rsp_ready_i,
  output pa_t                   rsp_pa_o,
  output op_e                   rsp_op_o,
  output logic                  rsp_region_hit_o,

  // CSR interface (flat for now; register-top wraps this)
  input  logic                  cfg_we_i,
  input  logic [3:0]            cfg_idx_i,
  input  region_t               cfg_wdata_i,
  input  logic                  cfg_commit_i,
  input  mode_e                 cfg_default_mode_i
);

  // ---------------------------------------------------------------------------
  // Region lookup (combinational)
  // ---------------------------------------------------------------------------
  region_t lookup_region;
  logic    lookup_hit;
  addr_map_region_table u_table (
    .clk_i,
    .rst_ni,
    .lookup_sa_i (req_sa_i),
    .lookup_region_o (lookup_region),
    .lookup_hit_o    (lookup_hit),
    .cfg_we_i,
    .cfg_idx_i,
    .cfg_wdata_i,
    .cfg_commit_i
  );

  // ---------------------------------------------------------------------------
  // XOR-hash mapper (combinational)
  // ---------------------------------------------------------------------------
  pa_t mapped_pa;
  addr_map_xor u_xor (
    .sa_i           (req_sa_i),
    .region_i       (lookup_region),
    .default_mode_i (cfg_default_mode_i),
    .pa_o           (mapped_pa)
  );

  // ---------------------------------------------------------------------------
  // 1-cycle output register with ready/valid handshake.
  // ---------------------------------------------------------------------------
  logic    rsp_valid_q;
  pa_t     rsp_pa_q;
  op_e     rsp_op_q;
  logic    rsp_hit_q;

  // We accept a new request whenever the response register is not holding
  // an unaccepted result.
  assign req_ready_o = !rsp_valid_q || rsp_ready_i;

  always_ff @(posedge clk_i or negedge rst_ni) begin : p_outreg
    if (!rst_ni) begin
      rsp_valid_q <= 1'b0;
      rsp_pa_q    <= '0;
      rsp_op_q    <= OP_READ;
      rsp_hit_q   <= 1'b0;
    end else begin
      // Pop the existing response if downstream took it.
      if (rsp_valid_q && rsp_ready_i) begin
        rsp_valid_q <= 1'b0;
      end
      // Push a new response if the input was accepted this cycle.
      if (req_valid_i && req_ready_o) begin
        rsp_valid_q <= 1'b1;
        rsp_pa_q    <= mapped_pa;
        rsp_op_q    <= req_op_i;
        rsp_hit_q   <= lookup_hit;
      end
    end
  end

  assign rsp_valid_o      = rsp_valid_q;
  assign rsp_pa_o         = rsp_pa_q;
  assign rsp_op_o         = rsp_op_q;
  assign rsp_region_hit_o = rsp_hit_q;

  // ---------------------------------------------------------------------------
  // SVA invariants
  // ---------------------------------------------------------------------------
`ifndef SYNTHESIS
  // 5: no spurious response.
  a_rsp_only_after_req : assert property (
    @(posedge clk_i) disable iff (!rst_ni)
    rsp_valid_o |-> $past(req_valid_i && req_ready_o)
  );

  // 2: bound checks. The struct widths already constrain the values
  // structurally; this is a belt-and-braces check that catches any
  // synthesis-tool truncation surprises.
  a_ch_bound  : assert property (@(posedge clk_i) rsp_pa_o.ch  < ChW'(NUM_CHANNELS));
  a_pch_bound : assert property (@(posedge clk_i) rsp_pa_o.pch < PChW'(NUM_PSEUDO_CHANNELS));
  a_bg_bound  : assert property (@(posedge clk_i) rsp_pa_o.bg  < BgW'(NUM_BANK_GROUPS));
  a_ba_bound  : assert property (@(posedge clk_i) rsp_pa_o.ba  < BaW'(NUM_BANKS_PER_GROUP));
`endif

endmodule : addr_map
